services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: research-backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./research_frontend
      dockerfile: Dockerfile
    container_name: research-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend