import React, { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';

// Initialize mermaid
mermaid.initialize({
  startOnLoad: false,
  theme: 'dark',
  securityLevel: 'loose',
  themeVariables: {
    background: '#181825',
    primaryColor: '#cba6f7',
    primaryTextColor: '#cdd6f4',
    lineColor: '#89b4fa',
    actorBorder: '#f38ba8',
  },
});

interface MermaidRendererProps {
  chartCode: string;
}

export const MermaidRenderer: React.FC<MermaidRendererProps> = ({ chartCode }) => {
  const [svg, setSvg] = useState<string>('');
  const [error, setError] = useState<string | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let isMounted = true;
    const renderChart = async () => {
      if (!chartCode.trim()) return;

      try {
        setError(null);
        const uniqueId = `mermaid-diag-${Math.random().toString(36).substring(2, 9)}`;
        
        // Clean chart code by trimming lines
        const cleanedCode = chartCode
          .split('\n')
          .map((line) => line.trim())
          .filter((line) => line.length > 0)
          .join('\n');

        const { svg: renderedSvg } = await mermaid.render(uniqueId, cleanedCode);
        
        if (isMounted) {
          setSvg(renderedSvg);
        }
      } catch (err: any) {
        console.error('Mermaid render error:', err);
        // Clear broken elements generated by mermaid render failure from the document body
        const badElement = document.getElementById(`d${chartCode}`);
        if (badElement) badElement.remove();
        
        if (isMounted) {
          setError(err.message || 'Syntax error in diagram definition');
        }
      }
    };

    renderChart();

    return () => {
      isMounted = false;
    };
  }, [chartCode]);

  if (error) {
    return (
      <div className="mermaid-error">
        <p className="error-title">Failed to render architecture diagram</p>
        <pre className="raw-code"><code>{chartCode}</code></pre>
      </div>
    );
  }

  return (
    <div 
      className="mermaid-svg-container"
      ref={containerRef}
      dangerouslySetInnerHTML={{ __html: svg || '<div class="mermaid-loading">Rendering diagram...</div>' }}
    />
  );
};
